[build]
  base = "saas-dashboard"
  command = "npm run build"
  publish = "build"

# Redirects and rewrites configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  CI = "false" # Prevents warnings being treated as errors in the build process
  NODE_VERSION = "16"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 